[options]
admin_passwd = admin
db_host = dpg-d9gvhh3bc2fs739crumg-a
db_user = nailshop_user
db_password = G5LDC2g8v7L7kKbshS4NvHcGrDwvSCDz
db_name = nailshop
http_interface = 0.0.0.0
http_port = 8069
log_level = info
logfile = /var/log/odoo/odoo.log
data_dir = /var/lib/odoo
max_cron_threads = 2
workers = 2
